web_app_MVC_01/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web_app_MVC_01.Models;

namespace web_app_MVC_01.Controllers;

[Route("Students")]
public class StudentController : Controller
{
    private static List<Student> listStudent = new List<Student>();

    public StudentController()
    {
        if (!listStudent.Any())
        {
            listStudent = new List<Student>()
            {
                new Student()
                {
                    Id = 101, Name = "Le Ba Quang", Branch = Branch.IT, DateOfBorth = new DateTime(2000, 08, 02),
                    Gender = Gender.Male, IsRegular = true, Address = "A1-2025", Email = "quanglb@gmail.com"
                },
                new Student()
                {
                    Id = 102, Name = "Le Ba Tung", Branch = Branch.IT, DateOfBorth = new DateTime(2007, 02, 26),
                    Gender = Gender.Male, IsRegular = true, Address = "A1-2025", Email = "tunglb@gmail.com"
                },
                new Student()
                {
                    Id = 103, Name = "Le Ba Do", Branch = Branch.IT, DateOfBorth = new DateTime(2006, 02, 11),
                    Gender = Gender.Male, IsRegular = true, Address = "A1-2025", Email = "dolb@gmail.com"
                },
                new Student()
                {
                    Id = 104, Name = "John Terry", Branch = Branch.CE, DateOfBorth = new DateTime(1982, 08, 02),
                    Gender = Gender.Male, IsRegular = true, Address = "A1-2023", Email = "terry@gmail.com"
                },
                new Student()
                {
                    Id = 105, Name = "Cole Palmer", Branch = Branch.EE, DateOfBorth = new DateTime(1998, 08, 02),
                    Gender = Gender.Male, IsRegular = false, Address = "A1-2021", Email = "palmer@gmail.com"
                },
                new Student()
                {
                    Id = 106, Name = "Yamal", Branch = Branch.BE, DateOfBorth = new DateTime(2003, 08, 02),
                    Gender = Gender.Male, IsRegular = false, Address = "A1-1999", Email = "yamal@gmail.com"
                }
            };
        }
    }

    [Route("List")]
    public IActionResult Index()
    {
        return View(listStudent);
    }

    [HttpGet("Add")]
    public IActionResult Create()
    {
        ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
        ViewBag.AllBranches = new List<SelectListItem>()
        {
            new SelectListItem { Text = "IT", Value = "1" },
            new SelectListItem { Text = "BE", Value = "2" },
            new SelectListItem { Text = "CE", Value = "3" },
            new SelectListItem { Text = "EE", Value = "4" }
        };
        return View();
    }

    [HttpPost("Add")]
    public IActionResult Create(Student s)
    {
        if (ModelState.IsValid)
        {
            s.Id = listStudent.Last().Id + 1;

            if (s.Avatar != null && s.Avatar.Length > 0)
            {
                var fileName = Path.GetFileName(s.Avatar.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                Directory.CreateDirectory(Path.GetDirectoryName(filePath)!);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    s.Avatar.CopyTo(stream);
                }

                s.AvatarUrl = fileName;
            }

            listStudent.Add(s);

            return RedirectToAction("Index");
        }

        ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
        ViewBag.AllBranches = new List<SelectListItem>()
        {
            new SelectListItem { Text = "None", Value = "0" },
            new SelectListItem { Text = "IT", Value = "1" },
            new SelectListItem { Text = "BE", Value = "2" },
            new SelectListItem { Text = "CE", Value = "3" },
            new SelectListItem { Text = "EE", Value = "4" }
        };
        return View();
    }

    [Route("ShowDemo")]
    public IActionResult ShowDemo(string name)
    {
        ViewBag.name = name;
        return View();
    }
}

web_app_MVC_01/ViewComponents/RenderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using web_app_MVC_01.Models;

namespace web_app_MVC_01.ViewComponents;

public class RenderViewComponent : ViewComponent
{
    private List<MenuItem> MenuItems = new();
    public RenderViewComponent()
    {
        MenuItems = new List<MenuItem>()
        {
            //new MenuItem() { Id = 1, Link = "/Branches/List", Name = "Branches" },
            new MenuItem() { Id = 1, Link = "/Students/List", Name = "Students" },
            //new MenuItem() { Id = 1, Link = "/Subjects/List", Name = "Subjects" },
            //new MenuItem() { Id = 1, Link = "/Courses/List", Name = "Courses" },
            new MenuItem() { Id = 1, Link = "/Learner/List", Name = "Learner" },
        };
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View("RenderLeftMenu", MenuItems);
    }
}

web_app_MVC_01/Views/Shared/Footer.cshtml
<!-- Begin Footer -->
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; 2023</div>
        </div>
    </div>
</footer>
<!-- End Footer -->

web_app_MVC_01/Views/Shared/TopNav.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="">Management System</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>

web_app_MVC_01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - web_app_MVC_01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/web_app_MVC_01.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">youngboi in da hood</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - web_app_MVC_01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

web_app_MVC_01/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>@ViewData["Title"] Manager System</title>
    <link href="~/css/site.css" rel="stylesheet"/>
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<!-- Begin Top nav -->
<partial name="TopNav"/>
<!-- End Top nav -->
<div id="layoutSidenav">
    @await Component.InvokeAsync("Render")
    <!-- Begin Right content -->
    <div id="layoutSidenav_content">
        <!-- Begin Main -->
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <!-- End Main -->
        <partial name="Footer"/>
    </div>
    <!-- End Right content -->
</div>

<script src="~/js/site.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>