web_app_MVC_01/Models/Learner.cs
using System.ComponentModel.DataAnnotations;

namespace web_app_MVC_01.Models;

public class Learner
{
    public Learner()
    {
        Enrollments = new HashSet<Enrollment>();
    }
    
    public int LearnerID { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; } = string.Empty;

    [Required]
    [StringLength(50)]
    public string FirstMidName { get; set; } = string.Empty;

    [DataType(DataType.Date)]
    public DateTime EnrollmentDate { get; set; }

    public int MajorID { get; set; }
    public Major? Major { get; set; }

    public ICollection<Enrollment> Enrollments { get; set; }
}

web_app_MVC_01/Controllers/LearnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web_app_MVC_01.Models;

namespace web_app_MVC_01.Controllers;

[Route("Learner")]
public class LearnerController : Controller
{
    private SchoolContext db;

    public LearnerController(SchoolContext _db)
    {
        db = _db;
    }

    #region View

    // [Route("List")]
    // public IActionResult Index()
    // {
    //     var data = db.Learners.Include(x => x.Major).ToList();
    //     return View(data);
    // }
    
    // [Route("List")]
    // public IActionResult Index(int page = 1)
    // {
    //     var learners = db.Learners.AsQueryable(); // giữ IQueryable để tối ưu
    //
    //     // Tính số trang
    //     int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);
    //     ViewBag.pageNum = pageNum;
    //     ViewBag.page = page; // gửi luôn trang hiện tại nếu muốn highlight
    //
    //     // Lấy dữ liệu trang hiện tại
    //     var result = learners
    //         .Skip(pageSize * (page - 1))
    //         .Take(pageSize)
    //         .Include(x => x.Major)
    //         .ToList();
    //
    //     return View(result);
    // }

    #endregion

    #region Create

    [HttpGet("Add")]
    public IActionResult Create()
    {
        var majors = new List<SelectListItem>(); // cách 1
        foreach (var item in db.Majors)
        {
            majors.Add(new SelectListItem { Text = item.MajorName, Value = item.MajorID.ToString() });
        }

        ViewBag.MajorID = majors;

        ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName"); // cách 2
        return View();
    }

    [HttpPost("Add")]
    [ValidateAntiForgeryToken]
    public IActionResult Create([Bind("FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
    {
        if (ModelState.IsValid)
        {
            db.Learners.Add(learner);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName");
        return View();
    }

    #endregion

    #region Update

    [HttpGet("Edit")]
    public IActionResult Edit(int id)
    {
        if (id == null || db.Learners == null)
        {
            return NotFound();
        }

        var learner = db.Learners.Find(id);
        if (learner == null)
        {
            return NotFound();
        }

        ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName", learner.MajorID);
        return View(learner);
    }

    [HttpPost("Edit")]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(int id, [Bind("LearnerID,FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
    {
        if (id != learner.LearnerID)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                db.Update(learner);
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LearnerExists(learner.LearnerID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName", learner.MajorID);
        return View(learner);
    }

    private bool LearnerExists(int id)
    {
        return (db.Learners?.Any(e => e.LearnerID == id)).GetValueOrDefault();
    }

    #endregion

    #region Remove

    public IActionResult Delete(int id)
    {
        if (id == null || db.Learners == null)
        {
            return NotFound();
        }

        var learner = db.Learners.Include(l => l.Major)
            .Include(e => e.Enrollments)
            .FirstOrDefault(m => m.LearnerID == id);

        if (learner == null)
        {
            return NotFound();
        }

        if (learner.Enrollments.Count() > 0)
        {
            return Content("This learner has some enrollments, can't delete!");
        }

        return View(learner);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
        if (db.Learners == null)
        {
            return Problem("Entity set 'Learners' is null.");
        }

        var learner = db.Learners.Find(id);
        if (learner != null)
        {
            db.Learners.Remove(learner);
        }

        db.SaveChanges();
        return RedirectToAction("Index");
    }

    #endregion

    private int pageSize = 3;
    [Route("List")]
    public IActionResult Index(int? mid)
    {
        var learners = db.Learners.ToList();
        
        if (mid != null)
        {
             learners = db.Learners.Where(x => x.MajorID == mid).Include(x => x.Major).ToList();
        }

        int pageNum = (int)Math.Ceiling((learners.Count) / (float)pageSize);

        ViewBag.pageNum = pageNum;
        var resp = learners.Take(pageSize).ToList();
        
        return View(resp);
        
    }
    
    [HttpGet("LearnerFilter")]
    public IActionResult LearnerFilter(int? mid, string? keyword, int? pageIndex)
    {
        //lấy toàn bộ learners trong dbset chuyển về IQuerrable<Learner> để dùng Lingq
        var learners = (IQueryable<Learner>)db.Learners;
        //lấy chỉ số trang, nếu chỉ số trang null thì gán ngầm định bằng 1
        int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);
        //nếu có mid thì lọc learner theo mid (chuyên ngành)
        if (mid != null)
        {
            learners = learners.Where(l => l.MajorID == mid); //lọc
            ViewBag.mid = mid; //gửi mid về view để ghi lại trên nav-trang
        }
        //nếu có keyword thì tìm kiếm theo tên
        if (!string.IsNullOrEmpty(keyword))
        {
            learners = learners.Where(l => l.FirstMidName.ToLower().Contains(keyword.ToLower())); //tìm kiếm
            ViewBag.keyword = keyword; //gửi keyword về view để ghi lại trên nav-trang
        }
        //tính số trang
        int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);
        ViewBag.pageNum = pageNum; //gửi số trang về view để hiển thị nav-trang
        //chọn dữ liệu trong trang hiện tại
        var result = learners.Skip(pageSize * (page - 1))
            .Take(pageSize)
            .Include(m => m.Major).ToList();
        return PartialView("LearnerTable", result);
    }

    [HttpGet("LearnerByMajorID")]
    public IActionResult LearnerByMajorID(int mid)
    {
        Console.WriteLine("mid: " + mid);
        var resp = db.Learners.Where(x => x.MajorID == mid).Include(x => x.Major).ToList();
        return PartialView("LearnerTable", resp);
    }
}

web_app_MVC_01/ViewComponents/MajorViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using web_app_MVC_01.Models;

namespace web_app_MVC_01.ViewComponents;

public class MajorViewComponent : ViewComponent
{
    private SchoolContext db;
    private List<Major> majors;

    public MajorViewComponent(SchoolContext db)
    {
        this.db = db;
        majors = this.db.Majors.ToList();
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View("RenderMajor", majors);
    }
}

web_app_MVC_01/Views/Learner/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "_MyLayout";
}

@model Learner

<div class="ms-2 mx-2">
    <h1>Create</h1>
    <form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Last Name" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="custom-select mr-sm-2"
                        asp-items="ViewBag.MajorID"></select>
                <span asp-validation-for="MajorID" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control" />
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

web_app_MVC_01/Views/Learner/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "_MyLayout";
}

@model Learner

<div class="ms-2 mx-2">
    <h1>Delete</h1>
    <h3>Are you sure you want to delete this?</h3>
    <h4>Learner</h4>
    <hr/>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Major)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Major.MajorName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
    </dl>

    <form asp-action="Delete" asp-route-id="@Model.LearnerID">
        <input type="hidden" asp-for="LearnerID" />
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

web_app_MVC_01/Views/Learner/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "_MyLayout";
}

@model Learner

<div class="ms-2 mx-2">
    <h1>Edit</h1>
    <div asp-validation-summary="All" class="text-danger"></div>

    <form asp-controller="Learner" asp-action="Edit" asp-route-id="@Model.LearnerID" method="post" class="mt-3">
        <input type="hidden" asp-for="LearnerID" />

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Last Name" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="custom-select mr-sm-2"
                        asp-items="@ViewBag.MajorID"></select>
                <span asp-validation-for="MajorID" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control" />
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
        </div>

        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Edit</button>
            </div>
        </div>
    </form>
</div>

web_app_MVC_01/Views/Learner/LeanerTable.cshtml
@model IEnumerable<Learner>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Mã</th>
        <th>Tên</th>
        <th>Họ</th>
        <th>Ngành</th>
        <th>Ngày Nhập Học</th>
        <th>Chức năng</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var s in Model)
    {
        <tr>
            <td>@s.LearnerID</td>
            <td>@s.FirstMidName</td>
            <td>@s.LastName</td>
            <td>@s.Major.MajorName</td>
            <td>@s.EnrollmentDate</td>
            <td>
                <a asp-action="Edit" asp-route-id="@s.LearnerID">Edit</a> |
                <a asp-action="Delete" asp-route-id="@s.LearnerID">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

web_app_MVC_01/Views/Learner/LearnerTable.cshtml
@model IEnumerable<Learner>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Mã</th>
        <th>Tên</th>
        <th>Họ</th>
        <th>Ngành</th>
        <th>Ngày Nhập Học</th>
        <th>Chức năng</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var s in Model)
    {
        <tr>
            <td>@s.LearnerID</td>
            <td>@s.FirstMidName</td>
            <td>@s.LastName</td>
            <td>@s.Major.MajorName</td>
            <td>@s.EnrollmentDate</td>
            <td>
                <a asp-action="Edit" asp-route-id="@s.LearnerID">Edit</a> |
                <a asp-action="Delete" asp-route-id="@s.LearnerID">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<ul class="pagination">
    @for (int i = 1; i <= ViewBag.pageNum; i++)
    {
        <li class="page-item" page="@i"
            @(ViewBag.mid != null ? "mid" + ViewBag.mid : "")
            @(ViewBag.keyword != null ? "keyword" + ViewBag.keyword : "")>
            <a class="page-link"@i></a>
        </li>
    }
</ul>

web_app_MVC_01/Views/Learner/index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "_MyLayout";
}

@model IEnumerable<Learner>

<div class="ms-2 mx-2">
    <h1>Learner List</h1>
    @await Component.InvokeAsync("Major")
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input id="keyword" class="form-control" name="keyword"
                   type="text" placeholder="Search learner" />
            <button id="btnSearch" class="btn btn-primary" type="button">
                <i class="fas fa-search"></i></button>
        </div>
    </form>
    <div id="content">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Mã</th>
                <th>Tên</th>
                <th>Họ</th>
                <th>Ngành</th>
                <th>Ngày Nhập Học</th>
                <th>Chức năng</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.LearnerID</td>
                    <td>@s.FirstMidName</td>
                    <td>@s.LastName</td>
                    <td>@s.Major.MajorName</td>
                    <td>@s.EnrollmentDate</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@s.LearnerID">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@s.LearnerID">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <ul class="pagination">
            @for (int i = 1; i <= ViewBag.pageNum; i++)
            {
            <li class="page-item" page="@i"
                @(ViewBag.mid != null ? "mid" + ViewBag.mid : "")
                @(ViewBag.keyword != null ? "keyword" + ViewBag.keyword : "")>
                <a class="page-link"@i></a>
            </li>
            }
        </ul>
    </div>
    <a asp-action="Create" class="btn btn-primary">Create New Student</a>
</div>

@section Scripts {
    <script>

        $('body').on('click', 'li.page-item', function (e) {
            var page = $(this).attr("page");
            var mid = $(this).attr("mid");
            var keyword = $(this).attr("keyword");
            var data = { mid: mid, keyword: keyword, pageIndex: page };
            console.log(mid)
            console.log(keyword)
            console.log(data)
            $.ajax({
                url: "/Learner/LearnerFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });

        $(".nav li").click(function (e) {
            var id = $(this).attr("id");
            var data = { mid: id };
            $.ajax({
                url: "/Learner/LearnerFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });

        $("button#btnSearch").click(function (e) {
            var keyword = $("#keyword").val();
            var data = { keyword: keyword };
            $.ajax({
                url: "/Learner/LearnerFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });

    $(document).on('click', '.nav-link', function (e) {
        e.preventDefault(); 

        var id = $(this).closest("li").attr("id"); 
        var data = { mid: id };
        
        console.log(id)
        console.log(data)

        $.ajax({
            url: "/Learner/LearnerByMajorID",
            data: data,
            success: function (response) {
            console.log(response)
                $("div#content").html(response);
            },
            error: function () {
                alert("Không thể load dữ liệu!");
            }
        });
    });

    
    </script>
}